### ISSUE TITLE
В новых версиях поведение изменено для

### ISSUE THREAD

**Issue by bscheshirwork** [lawejr/PhpStorm-hotkeys#3]
Move Line Up	CMD + Shift + up	Ctrl + Shift + up	Переместить текущую строку на одну строку вверх
Move Line Down	CMD + Shift + down	Ctrl + Shift + down	Переместить текущую строку на одну строку вниз

**Comment by lawejr** [comment]
Спасибо, поправил. 
Кстати вышеописанные комбинации тоже валидны, только двигают не строку, а блок кода целиком, в котором находится курсор.

**Comment by bscheshirwork** [comment]
Блок кода двигается по "умным" алгоритмам, что в 99% случаев просто ломает код...
